"""alteracao_integracao_login_usuario_chave_unica

Revision ID: 057b3b0b1477
Revises: 282c8cc0398c
Create Date: 2024-07-22 17:44:14.546369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057b3b0b1477'
down_revision: Union[str, None] = '282c8cc0398c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usuario', ['login_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    # ### end Alembic commands ###
