"""models de orçamento

Revision ID: 0d28e670e6f3
Revises: 2646a2bc4507
Create Date: 2024-10-02 20:30:35.979696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d28e670e6f3'
down_revision: Union[str, None] = '2646a2bc4507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento_status',
    sa.Column('orcamento_status_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_exclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.empresa_id'], ),
    sa.ForeignKeyConstraint(['titulo'], ['cliente.cliente_id'], ),
    sa.PrimaryKeyConstraint('orcamento_status_id')
    )
    op.create_table('orcamento_tipo',
    sa.Column('orcamento_tipo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('responsavel_cadastro_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('data_exclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.empresa_id'], ),
    sa.PrimaryKeyConstraint('orcamento_tipo_id')
    )
    op.create_table('orcamento',
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('orcamento_status_id', sa.Integer(), nullable=True),
    sa.Column('orcamento_tipo_id', sa.Integer(), nullable=True),
    sa.Column('data_exclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.cliente_id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.empresa_id'], ),
    sa.ForeignKeyConstraint(['orcamento_status_id'], ['orcamento_status.orcamento_status_id'], ),
    sa.ForeignKeyConstraint(['orcamento_tipo_id'], ['orcamento_tipo.orcamento_tipo_id'], ),
    sa.PrimaryKeyConstraint('orcamento_id')
    )
    op.create_table('orcamento_item',
    sa.Column('orcamento_item_id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('quantidade_orcamento', sa.Integer(), nullable=False),
    sa.Column('data_exclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.orcamento_id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.produto_id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.servico_id'], ),
    sa.PrimaryKeyConstraint('orcamento_item_id')
    )
    op.create_foreign_key(None, 'fatura', 'orcamento', ['orcamento_id'], ['orcamento_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fatura', type_='foreignkey')
    op.drop_table('orcamento_item')
    op.drop_table('orcamento')
    op.drop_table('orcamento_tipo')
    op.drop_table('orcamento_status')
    # ### end Alembic commands ###
