"""alterada model de orcamento

Revision ID: 16dc0a3b52a5
Revises: 8ae77f2c369f
Create Date: 2024-10-25 21:27:55.701866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16dc0a3b52a5'
down_revision: Union[str, None] = '8ae77f2c369f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orcamento_orcamento_tipo_id_fkey', 'orcamento', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('orcamento_orcamento_tipo_id_fkey', 'orcamento', 'orcamento_tipo', ['orcamento_tipo_id'], ['orcamento_tipo_id'])
    # ### end Alembic commands ###
