"""adicionado campo de aprovacao de serviço

Revision ID: 2646a2bc4507
Revises: eb7718405c90
Create Date: 2024-09-29 16:38:26.847506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2646a2bc4507'
down_revision: Union[str, None] = 'eb7718405c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('aprovado', sa.Boolean(), default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servico', 'aprovado')
    # ### end Alembic commands ###
