"""alteracao_integracao_login_usuario

Revision ID: 282c8cc0398c
Revises: 6ddb7f28841e
Create Date: 2024-07-21 19:36:16.424529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282c8cc0398c'
down_revision: Union[str, None] = '6ddb7f28841e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('login_usuario_id_fkey', 'login', type_='foreignkey')
    op.drop_column('login', 'usuario_id')
    op.add_column('usuario', sa.Column('login_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'usuario', 'login', ['login_id'], ['login_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'login_id')
    op.add_column('login', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('login_usuario_id_fkey', 'login', 'usuario', ['usuario_id'], ['usuario_id'])
    # ### end Alembic commands ###
