"""removido campo aprovado do orcamento

Revision ID: 42a055067377
Revises: dde404810e88
Create Date: 2024-11-02 17:03:23.694050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a055067377'
down_revision: Union[str, None] = 'dde404810e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamento', 'aprovado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamento', sa.Column('aprovado', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
