"""previsao_entrega no model de servicos

Revision ID: 495be960932e
Revises: e9d8a14a066a
Create Date: 2024-09-21 22:11:46.835960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495be960932e'
down_revision: Union[str, None] = 'e9d8a14a066a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('previsao_entrega', sa.DateTime(), nullable=True))
    op.add_column('servico', sa.Column('cliente_solicitante', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'servico', 'cliente', ['cliente_solicitante'], ['cliente_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servico', type_='foreignkey')
    op.drop_column('servico', 'cliente_solicitante')
    op.drop_column('servico', 'previsao_entrega')
    # ### end Alembic commands ###
