"""alteradas models de cliente e orcamento_status

Revision ID: 64fff53cb997
Revises: 16dc0a3b52a5
Create Date: 2024-10-26 21:48:13.113526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64fff53cb997'
down_revision: Union[str, None] = '16dc0a3b52a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.drop_column('cliente', 'lead_conversao')
    op.alter_column('orcamento_status', 'titulo',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orcamento_status', 'titulo',
               existing_type=sa.String(length=500),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('cliente', sa.Column('lead_conversao', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cliente', 'lead_id')
    # ### end Alembic commands ###
