"""correcao_empresa

Revision ID: 81b3913b045c
Revises: 057b3b0b1477
Create Date: 2024-07-23 22:51:38.213032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b3913b045c'
down_revision: Union[str, None] = '057b3b0b1477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'empresa', ['cnpj'])
    op.create_unique_constraint(None, 'empresa', ['cpf'])
    op.drop_constraint('empresa_responsavel_cadastro_id_fkey', 'empresa', type_='foreignkey')
    op.create_foreign_key(None, 'empresa', 'login', ['responsavel_cadastro_id'], ['login_id'])
    op.create_unique_constraint(None, 'usuario', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'empresa', type_='foreignkey')
    op.create_foreign_key('empresa_responsavel_cadastro_id_fkey', 'empresa', 'usuario', ['responsavel_cadastro_id'], ['usuario_id'])
    op.drop_constraint(None, 'empresa', type_='unique')
    op.drop_constraint(None, 'empresa', type_='unique')
    # ### end Alembic commands ###
