"""criar model de venda

Revision ID: 832874966bcb
Revises: 9e556308e3f6
Create Date: 2024-11-01 00:12:05.196825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832874966bcb'
down_revision: Union[str, None] = '9e556308e3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venda_status',
    sa.Column('venda_status_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_cadastro_id', sa.Integer(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_exclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.empresa_id'], ),
    sa.PrimaryKeyConstraint('venda_status_id')
    )
    op.create_table('venda',
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('venda_status_id', sa.Integer(), nullable=True),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_cadastro_id', sa.Integer(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_exclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.empresa_id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.orcamento_id'], ),
    sa.ForeignKeyConstraint(['venda_status_id'], ['venda_status.venda_status_id'], ),
    sa.PrimaryKeyConstraint('venda_id')
    )
    op.add_column('orcamento', sa.Column('venda_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orcamento', 'venda', ['venda_id'], ['venda_id'])
    op.alter_column('orcamento_status', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('servico_tipo', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico_tipo', sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.alter_column('orcamento_status', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'orcamento', type_='foreignkey')
    op.drop_column('orcamento', 'venda_id')
    op.drop_table('venda_status')
    op.drop_table('venda')
    # ### end Alembic commands ###
