"""add empresa_id a categorias de produtos

Revision ID: 8ae77f2c369f
Revises: 91ca1a457c70
Create Date: 2024-10-24 19:28:51.115217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae77f2c369f'
down_revision: Union[str, None] = '91ca1a457c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto_categoria', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('produto_subcategoria', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('produto_tipo', sa.Column('empresa_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto_tipo', 'empresa_id')
    op.drop_column('produto_subcategoria', 'empresa_id')
    op.drop_column('produto_categoria', 'empresa_id')
    # ### end Alembic commands ###
