"""remover solicitante do model de serviço

Revision ID: 91ca1a457c70
Revises: 40fa5a97ffe3
Create Date: 2024-10-19 23:47:56.607079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91ca1a457c70'
down_revision: Union[str, None] = '40fa5a97ffe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('previsao_entrega_dias', sa.Integer(), nullable=True))
    op.drop_constraint('servico_cliente_solicitante_id_fkey', 'servico', type_='foreignkey')
    op.drop_column('servico', 'previsao_entrega')
    op.drop_column('servico', 'cliente_solicitante_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('cliente_solicitante_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('servico', sa.Column('previsao_entrega', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('servico_cliente_solicitante_id_fkey', 'servico', 'cliente', ['cliente_solicitante_id'], ['cliente_id'])
    op.drop_column('servico', 'previsao_entrega_dias')
    # ### end Alembic commands ###
