"""alterada_realcao_de_produtos

Revision ID: 9b4a1011b4c3
Revises: d3bbe7ccbc99
Create Date: 2024-08-05 20:08:52.066920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4a1011b4c3'
down_revision: Union[str, None] = 'd3bbe7ccbc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE produto ALTER COLUMN responsavel_cadastro_id TYPE INTEGER USING responsavel_cadastro_id::integer;")
    op.drop_constraint('produto_produto_subcategoria_id_fkey', 'produto', type_='foreignkey')
    op.drop_constraint('produto_produto_categoria_id_fkey', 'produto', type_='foreignkey')
    op.drop_column('produto', 'produto_categoria_id')
    op.drop_column('produto', 'produto_subcategoria_id')
    op.add_column('produto_subcategoria', sa.Column('produto_categoria_id', sa.Integer(), nullable=True))
    op.drop_constraint('produto_subcategoria_usuario_id_fkey', 'produto_subcategoria', type_='foreignkey')
    op.create_foreign_key(None, 'produto_subcategoria', 'produto_categoria', ['produto_categoria_id'], ['produto_categoria_id'])
    op.drop_column('produto_subcategoria', 'usuario_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto_subcategoria', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'produto_subcategoria', type_='foreignkey')
    op.create_foreign_key('produto_subcategoria_usuario_id_fkey', 'produto_subcategoria', 'usuario', ['usuario_id'], ['usuario_id'])
    op.drop_column('produto_subcategoria', 'produto_categoria_id')
    op.add_column('produto', sa.Column('produto_subcategoria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('produto', sa.Column('produto_categoria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('produto_produto_categoria_id_fkey', 'produto', 'produto_categoria', ['produto_categoria_id'], ['produto_categoria_id'])
    op.create_foreign_key('produto_produto_subcategoria_id_fkey', 'produto', 'produto_subcategoria', ['produto_subcategoria_id'], ['produto_subcategoria_id'])
    op.alter_column('produto', 'responsavel_cadastro_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###
