"""add_coluna_preco_custo_em_produto

Revision ID: 9c5dbdf942ba
Revises: e0ead6774c6c
Create Date: 2024-08-24 18:06:14.988273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5dbdf942ba'
down_revision: Union[str, None] = 'e0ead6774c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('produto', sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.drop_column('produto', 'preco')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('preco', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('produto', 'preco_custo')
    op.drop_column('produto', 'preco_venda')
    # ### end Alembic commands ###
