"""campos de descrição e observação no model de orcamento

Revision ID: 9e556308e3f6
Revises: a563b7b97854
Create Date: 2024-10-27 15:56:10.588531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e556308e3f6'
down_revision: Union[str, None] = 'a563b7b97854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamento', sa.Column('descricao', sa.String(length=1000), nullable=True))
    op.add_column('orcamento', sa.Column('observacoes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamento', 'observacoes')
    op.drop_column('orcamento', 'descricao')
    # ### end Alembic commands ###
