"""criado_rel_servico_produto_model

Revision ID: a26f2a6c90ba
Revises: a5b00ad018c2
Create Date: 2024-08-25 17:55:44.794672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26f2a6c90ba'
down_revision: Union[str, None] = 'a5b00ad018c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rel_servico_produto',
    sa.Column('rel_servico_produto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rel_servico_produto_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_servico_produto')
    # ### end Alembic commands ###
