"""responsavel cadastro no model de orcamento

Revision ID: a563b7b97854
Revises: 64fff53cb997
Create Date: 2024-10-26 23:47:58.452408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a563b7b97854'
down_revision: Union[str, None] = '64fff53cb997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamento', sa.Column('responsavel_cadastro_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamento', 'responsavel_cadastro_id')
    # ### end Alembic commands ###
