"""criado_servico_model

Revision ID: a5b00ad018c2
Revises: 8cf45dc55348
Create Date: 2024-08-25 17:52:16.149191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b00ad018c2'
down_revision: Union[str, None] = '8cf45dc55348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servico_tipo',
    sa.Column('servico_tipo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('imagem', sa.String(length=300), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('responsavel_cadastro_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('data_exclusao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('servico_tipo_id')
    )
    op.create_table('servico',
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('preco_mao_de_obra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('imagem', sa.String(length=300), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('responsavel_cadastro_id', sa.Integer(), nullable=True),
    sa.Column('detalhes_opcionais', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('data_exclusao', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.empresa_id'], ),
    sa.PrimaryKeyConstraint('servico_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servico')
    op.drop_table('servico_tipo')
    # ### end Alembic commands ###
