"""relacoes_de_produtos

Revision ID: a792773b250a
Revises: c33cdb1f7981
Create Date: 2024-08-24 16:40:41.145699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a792773b250a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('produto_categoria_id', sa.Integer(), nullable=False))
    op.add_column('produto', sa.Column('produto_subcategoria_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'produto', 'produto_subcategoria', ['produto_subcategoria_id'], ['produto_subcategoria_id'])
    op.create_foreign_key(None, 'produto', 'produto_categoria', ['produto_categoria_id'], ['produto_categoria_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'produto_subcategoria_id')
    op.drop_column('produto', 'produto_categoria_id')
    # ### end Alembic commands ###
