"""lead_funil_e_add_campos_de_data

Revision ID: ae2d23ba95ce
Revises: 81b3913b045c
Create Date: 2024-07-24 18:00:21.621884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2d23ba95ce'
down_revision: Union[str, None] = '81b3913b045c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_funil',
    sa.Column('funil_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('imagem', sa.String(length=300), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_exclusao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('funil_id')
    )
    op.drop_column('cliente', 'status')
    op.add_column('login', sa.Column('data_exclusao', sa.DateTime(), nullable=True))
    op.add_column('login_empresa', sa.Column('data_exclusao', sa.DateTime(), nullable=True))
    op.drop_column('orcamento', 'delet')
    op.add_column('permissao', sa.Column('data_exclusao', sa.DateTime(), nullable=True))
    op.add_column('profissao', sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profissao', 'data_cadastro')
    op.drop_column('permissao', 'data_exclusao')
    op.add_column('orcamento', sa.Column('delet', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('login_empresa', 'data_exclusao')
    op.drop_column('login', 'data_exclusao')
    op.add_column('cliente', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('lead_funil')
    # ### end Alembic commands ###
