"""adicionar_constraint_unique_sku_produto

Revision ID: b46052c344b0
Revises: 2b731615f075
Create Date: 2025-08-15 11:58:51.318218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46052c344b0'
down_revision: Union[str, None] = '2b731615f075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Primeiro, identificamos e tratamos SKUs duplicados
    # Para duplicatas, alteramos o SKU para NULL nos registros secundários
    op.execute("""
        UPDATE produto 
        SET sku = NULL
        WHERE sku IS NOT NULL 
        AND sku IN (
            SELECT sku 
            FROM (
                SELECT sku, COUNT(*) as count 
                FROM produto 
                WHERE sku IS NOT NULL 
                GROUP BY sku 
                HAVING COUNT(*) > 1
            ) duplicates
        )
        AND produto_id NOT IN (
            SELECT MIN(produto_id) 
            FROM (SELECT * FROM produto) p2 
            WHERE p2.sku = produto.sku 
            AND p2.sku IS NOT NULL
            GROUP BY p2.sku
        )
    """)
    
    # Agora podemos criar a constraint unique
    op.create_unique_constraint('uq_produto_sku', 'produto', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove a constraint unique
    op.drop_constraint('uq_produto_sku', 'produto', type_='unique')
    # ### end Alembic commands ###
