"""adicionada_sigla_em_produto_subcategoria

Revision ID: cedc32ca4805
Revises: 9b4a1011b4c3
Create Date: 2024-08-05 20:20:20.235132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedc32ca4805'
down_revision: Union[str, None] = '9b4a1011b4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto_subcategoria', sa.Column('sigla', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto_subcategoria', 'sigla')
    # ### end Alembic commands ###
