"""corrigido campo id de servico

Revision ID: d185d7d2856a
Revises: e10a9d25a6f7
Create Date: 2024-09-29 15:09:52.030063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd185d7d2856a'
down_revision: Union[str, None] = 'e10a9d25a6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
