"""removida_relacao_de_cadastro_de_produtos

Revision ID: d3bbe7ccbc99
Revises: ae2d23ba95ce
Create Date: 2024-08-01 21:32:03.015425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bbe7ccbc99'
down_revision: Union[str, None] = 'ae2d23ba95ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produto_categoria', 'sigla',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.drop_constraint('produto_categoria_responsavel_cadastro_id_fkey', 'produto_categoria', type_='foreignkey')
    op.add_column('produto_subcategoria', sa.Column('responsavel_cadastro_id', sa.Integer(), nullable=True))
    op.drop_column('produto_subcategoria', 'responsavel_cadastro')
    op.add_column('produto_tipo', sa.Column('responsavel_cadastro_id', sa.Integer(), nullable=True))
    op.drop_column('produto_tipo', 'responsavel_cadastro')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto_tipo', sa.Column('responsavel_cadastro', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('produto_tipo', 'responsavel_cadastro_id')
    op.add_column('produto_subcategoria', sa.Column('responsavel_cadastro', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('produto_subcategoria', 'responsavel_cadastro_id')
    op.create_foreign_key('produto_categoria_responsavel_cadastro_id_fkey', 'produto_categoria', 'usuario', ['responsavel_cadastro_id'], ['usuario_id'])
    op.alter_column('produto_categoria', 'sigla',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('produto', 'responsavel_cadastro_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###
