"""novos campos de orcamento

Revision ID: dde404810e88
Revises: 832874966bcb
Create Date: 2024-11-02 16:47:40.557071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde404810e88'
down_revision: Union[str, None] = '832874966bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamento', sa.Column('aprovado', sa.Boolean(), nullable=True))
    op.add_column('orcamento', sa.Column('data_aprovacao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamento', 'data_aprovacao')
    op.drop_column('orcamento', 'aprovado')
    # ### end Alembic commands ###
