"""relacoes_de_produtos_corrigidas

Revision ID: e0ead6774c6c
Revises: a792773b250a
Create Date: 2024-08-24 17:01:36.459853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ead6774c6c'
down_revision: Union[str, None] = 'a792773b250a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
