"""adição de campo de lead opcional em cliente

Revision ID: e10a9d25a6f7
Revises: ea22b9a39bb5
Create Date: 2024-09-29 15:06:20.406772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10a9d25a6f7'
down_revision: Union[str, None] = 'ea22b9a39bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('lead_conversao', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'lead_conversao')
    # ### end Alembic commands ###
