"""Alterada relação produto e estoque e adicionado estoque_tipo

Revision ID: e9d8a14a066a
Revises: a26f2a6c90ba
Create Date: 2024-09-14 16:07:24.436904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Inspector

# revision identifiers, used by Alembic.
revision: str = 'e9d8a14a066a'
down_revision: Union[str, None] = 'a26f2a6c90ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_tipo',
    sa.Column('estoque_tipo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_exclusao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('estoque_tipo_id')
    )
    op.add_column('estoque', sa.Column('estoque_tipo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'estoque', 'estoque_tipo', ['estoque_tipo_id'], ['estoque_tipo_id'])

    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)

    # Obtenha todas as tabelas no banco de dados
    tables = inspector.get_table_names()

    for table in tables:
        # Obtenha as colunas de cada tabela
        columns = inspector.get_columns(table)
        for column in columns:
            if column['name'] == 'data_cadastro' and isinstance(column['type'], sa.types.DateTime):
                # Use SQL direto para alterar a coluna e adicionar CURRENT_TIMESTAMP como valor padrão
                op.execute(f"""
                               ALTER TABLE {table}
                               ALTER COLUMN data_cadastro
                               SET DEFAULT CURRENT_TIMESTAMP;
                           """)
            if column['name'] == 'status' and isinstance(column['type'], sa.types.Boolean):
                # Use SQL direto para alterar a coluna e adicionar CURRENT_TIMESTAMP como valor padrão
                op.execute(f"""
                               ALTER TABLE {table}
                               ALTER COLUMN status
                               SET DEFAULT true;
                           """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estoque', type_='foreignkey')
    op.drop_column('estoque', 'estoque_tipo_id')
    op.drop_table('estoque_tipo')
    # ### end Alembic commands ###
