"""correção de serviços

Revision ID: ea22b9a39bb5
Revises: 495be960932e
Create Date: 2024-09-29 14:48:40.414915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea22b9a39bb5'
down_revision: Union[str, None] = '495be960932e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rel_servico_produto', 'produto', ['produto_id'], ['produto_id'])
    op.create_foreign_key(None, 'rel_servico_produto', 'servico', ['servico_id'], ['servico_id'])
    op.add_column('servico', sa.Column('servico_tipo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'servico', 'servico_tipo', ['servico_tipo_id'], ['servico_tipo_id'])
    op.add_column('servico_tipo', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'servico_tipo', 'empresa', ['empresa_id'], ['empresa_id'])
    op.drop_column('servico_tipo', 'imagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico_tipo', sa.Column('imagem', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'servico_tipo', type_='foreignkey')
    op.drop_column('servico_tipo', 'empresa_id')
    op.drop_constraint(None, 'servico', type_='foreignkey')
    op.drop_column('servico', 'servico_tipo_id')
    op.drop_constraint(None, 'rel_servico_produto', type_='foreignkey')
    op.drop_constraint(None, 'rel_servico_produto', type_='foreignkey')
    # ### end Alembic commands ###
