"""adicionado campo de sku a produto

Revision ID: eb7718405c90
Revises: d185d7d2856a
Create Date: 2024-09-29 16:24:35.624679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7718405c90'
down_revision: Union[str, None] = 'd185d7d2856a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('sku', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'sku')
    # ### end Alembic commands ###
