"""adicionado valor venda e indicador de ordem de serviço

Revision ID: f3ae46061802
Revises: 42a055067377
Create Date: 2024-11-06 20:44:29.356377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ae46061802'
down_revision: Union[str, None] = '42a055067377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venda', sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False,
                                     server_default="0.00"))
    op.add_column('venda',
                  sa.Column('gera_ordem_servico', sa.Boolean(), nullable=False, server_default=sa.text('false')))


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venda', 'gera_ordem_servico')
    op.drop_column('venda', 'valor')
    # ### end Alembic commands ###
