from models.cliente_model import Base as ClienteBase, ClienteModel
from models.produto_model import Base as ProdutoBase, ProdutoModel
from models.empresa_model import Base as EmpresaBase, EmpresaModel
from models.estoque_model import Base as EstoqueBase, EstoqueModel
from models.fatura_item_model import Base as FaturaItemBase, FaturaItemModel
from models.fatura_model import Base as FaturaBase, FaturaModel
from models.lead_model import Base as LeadBase, LeadModel
from models.orcamento_item_model import Base as Orcamento_itemBase, OrcamentoItemModel
from models.orcamento_model import Base as OrcamentoBase, OrcamentoModel
from models.pais_model import Base as PaisBase, PaisModel
from models.produto_categorias_model import Base as ProdutoCategoriaBase, ProdutoCategoriaModel
from models.produto_subcategorias_model import Base as ProdutoSubcategoriaBase, ProdutoSubategoriaModel
from models.produto_tipos_model import Base as Produto_tiposBase, ProdutoTipoModel
from models.profissao_model import Base as ProfissaoBase, ProfissaoModel
from models.usuario_model import Base as UsuarioBase, UsuarioModel
from models.login_empresa import Base as LoginEmpresaBase, LoginEmpresaModel
from models.login_permissao_model import Base as LoginPermissaoBase, LoginPermissaoModel
from models.login_model import Base as LoginBase, LoginModel
from models.permissao_model import Base as PermissaoBase, PermissaoModel
